"use client";
import React, { useState } from "react";
import { FileCheck, Copy, Check, ShieldCheck, Download, X } from "lucide-react";

interface PostMortemModalProps {
  isOpen: boolean;
  onClose: () => void;
  incidentTitle: string;
}

export const PostMortemModal: React.FC<PostMortemModalProps> = ({ isOpen, onClose, incidentTitle }) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const postMortemContent = `# 📋 Incident Post-Mortem Report
**Incident ID**: #INC-0824  
**Title**: ${incidentTitle}  
**Status**: RESOLVED  
**Severity**: CRITICAL (P1)  
**Detection Time**: 2026-08-24 02:14:00 UTC  
**Resolution Time**: 2026-08-24 02:15:48 UTC  
**MTTD**: 28 seconds  
**MTTR**: 1.8 minutes  

---

## 🔍 Root Cause Analysis
Deployment #4c21e90 applied database migration \`049_add_orders_user_fk.sql\`, adding an unindexed foreign key constraint directly to the live \`orders\` table. This acquired an \`AccessExclusiveLock\`, blocking all concurrent checkout queries and causing HTTP 500 errors to spike to 48.2%.

## 🛡️ TrueForge Harness Autonomous Remediation
1. **Telemetry Scout (MCP)**: Identified 18 blocked transactions via PostgreSQL pg_locks and traced latency spike in Prometheus.
2. **Sandbox Bisector**: Cloned repository into TrueForge isolated container sandbox, ran \`git bisect\` to isolate commit #4c21, and tested a non-blocking rollback patch (48/48 tests passed).
3. **Blast-Radius Auditor**: Calculated risk score (74/100) and verified 0% data loss potential.
4. **Human-in-the-Loop Gate**: TrueForge paused execution with a cryptographic nonce. Human SRE verified the SQL diff and signed off.
5. **Execution**: Dropped blocking constraint and created non-blocking index \`CONCURRENTLY\`.

## 📜 Cryptographic Merkle Proof
- **Incident Merkle Root Hash**: \`0x9f4a8b2c1e0d3f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a\`
- **Compliance Certification**: SOC2 / ISO 27001 Tamper-Evident Incident Dossier Verified.
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(postMortemContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="w-full max-w-2xl bg-zinc-950 border border-emerald-500/40 rounded-2xl shadow-[0_0_50px_rgba(16,185,129,0.15)] overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        <div className="px-6 py-4 bg-emerald-500/10 border-b border-emerald-500/20 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <FileCheck className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-mono font-bold text-emerald-300 uppercase tracking-wider">
                Automated Incident Post-Mortem Dossier
              </h2>
              <p className="text-xs text-zinc-400 font-sans">
                Generated by PostMortemScribe with cryptographic Merkle proof.
              </p>
            </div>
          </div>

          <button onClick={onClose} className="p-1 rounded-lg text-zinc-400 hover:text-white transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 max-h-[60vh] overflow-y-auto font-mono text-xs text-zinc-300 whitespace-pre-wrap leading-relaxed bg-black/40">
          {postMortemContent}
        </div>

        <div className="px-6 py-3.5 bg-zinc-900 border-t border-zinc-800 flex items-center justify-between">
          <div className="flex items-center gap-2 text-[10px] font-mono text-emerald-400">
            <ShieldCheck className="w-4 h-4" />
            <span>Merkle Proof Verified (Zero Tampering)</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="px-4 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-zinc-200 font-mono text-xs flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? "Copied!" : "Copy Markdown"}
            </button>
            <button
              onClick={onClose}
              className="px-4 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-mono text-xs font-bold transition-colors cursor-pointer"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
